spring:
  application:
    name: user-service-api
  data:
   mongodb:
     uri: ${DB_MONGO_URI}
     auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'Component responsible for user management'
    version: '1.0.0'
