spring:
  application:
    name: user-service-api
  data:
   mongodb:
     uri: 'mongodb+srv://wilsonevangelista22_db_user:<db_password>@cluster0.fhjqzc8.mongodb.net/helpdeskdb?appName=Cluster0'
     auto-index-creation: true