spring:
  application:
    name: user-service-api
  data:
   mongodb:
     uri: ${DB_MONGO_URI}
     auto-index-creation: true
    # Conex√£o com o MongoDB local
   #uri: mongodb://localhost:27017/helpdeskdb
